### ISSUE TITLE
Question: how does it compare to photorec?

### ISSUE THREAD

**Issue by elektronik2k5** [saintmarina/undelete_jpg#4]
I saw you even mentioned photorec. How do they compare? How do they differ?

**Comment by saintmarina** [comment]
PhotoRec is far more superior software that undelete_jpg. 
Notable differences are: 
• PhotoRec recovers multiple types of files https://www.cgsecurity.org/wiki/File_Formats_Recovered_By_PhotoRec, when undelete_jpg recovers only .jpg files.
• PhotoRec supports fragmented file systems.
• Check out more PhotoRec features here https://en.wikipedia.org/wiki/PhotoRec#Functionality
