### ISSUE TITLE
Recovered JPGs seem to be corrupted

### ISSUE THREAD

**Issue by ekkoflok** [saintmarina/undelete_jpg#5]
Hi,
Thanks for a great tool! 
It happily recovers a lot of jpgs but most of them seem to be corrupted - is this the expected behaviour? I guess it could be due to false matches or maybe missing header.

**Comment by saintmarina** [comment]
If those corrupted files don't open:
- it could be that they are damaged beyond repair. Like the information that went into the jpg file header makes no sense (e.g. width = 5 million pixels). 

- my program has bugs and you should try other tools ([ProtoRec](https://www.cgsecurity.org/wiki/PhotoRec))

If those corrupted files open but look damaged, incomplete, or missing pixels:

-  this behavior is expected. The jpg you are trying to recover is deleted. Some data could have already been overwritten.

**Comment by ekkoflok** [comment]
Ok, thanks for the answer!
